[build]
  command = "npm run build"
  publish = ".output/public" # This is where your static files will be generated
  functions = ".netlify/functions" # Netlify Functions directory for SSR

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

